name = "NewtonsMethod"
uuid = "b85579f4-5533-4d2f-8fda-c25ebce311db"
authors = ["Tyler Ransom <tyleransom@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
